version: 0.2

phases:
  pre_build:
    commands:
      # Prevent files from haing a timestamp before 1980
      - find . -mtime +10950 -exec touch {} \;
  
  build:
     commands:
     - |
          #Package cloudFormation and create an export file (-secondary required for backwards compatibility for production release)
          aws cloudformation package --template-file template.yaml --s3-bucket "$S3_BUCKET" --s3-prefix $PROJECT_NAME --output-template-file template-export.yml 
          #--metadata "codeBuildId"=$CODEBUILD_BUILD_ID
  post_build:
    commands:
    - echo "build"
      
artifacts:
  type: zip
  files:
    - template-export.yml
    - buildspec.yml
    - template.yaml
    
