version: 0.2

phases:
  pre_build:
    commands:
      # Prevent files from haing a timestamp before 1980
      - find . -mtime +10950 -exec touch {} \;
  
  build:
     commands:
     - |
          
          aws cloudformation package --template-file template.yaml --s3-bucket shaurya-ecs --s3-prefix $serverless-application --output-template-file template.export.yaml 
          #aws cloudformation package --template-file template.yaml --s3-bucket "$S3_BUCKET" 
          #--s3-prefix $serverless-application --output-template-file template-export.yml --metadata "codeBuildId"=$CODEBUILD_BUILD_ID,"ENVIRONMENT"=$Stage
          #aws cloudformation package --template-file template.yaml --s3-bucket "$S3_BUCKET" --s3-prefix $serverless-application --output-template-file template-export-secondary.yml --metadata "codeBuildId"=$CODEBUILD_BUILD_ID,"ENVIRONMENT"=$Stage
  post_build:
    commands:
    - echo "build"
      
artifacts:
  type: zip
  files:
    - template.export.yml
    - buildspec.yml
    - template.yaml
    
