#cloud formation template to create ECR repo.
AWSTemplateFormatVersion: 2010-09-09
Description: This template is for deployment of ecr docker  image
Parameters:
  ProjectName:
    Type: String
  Stage:
    Type: String
   StageShortCode:
    Type: String
  regionShortCode:
    Type: String
     
Resources:
  ECRTestRepository
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:'ecr-test-${StageShortCode}-${regionShortCode}-repo*
    RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: UpdatedRegistryPolicy
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::113184785079:root'
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiatLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:PutLifecyclePolicy"
              - "ecr:DeleteLifecyclePolicy"
              - "ecr:StartImageScan"
              - "ecr:DescribeImageScanFindings"
              
    
